Repository RedHatQE/ci-jobs-trigger, pull requests merged in 2024-03, with the labels that each got.

#20 [LPTOCPCI-1153] Add a hyperlink to specific build logs in slack message
  ci_jobs_trigger/libs/openshift_ci/re_trigger/re_trigger.py
  ci_jobs_trigger/libs/openshift_ci/utils/constants.py
Labels: verified, size/XS, can-be-merged, approved-myakove, branch-main, commented-calebevans, commented-myakove

#27 get_config: log exception error on fail
  ci_jobs_trigger/utils/general.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#29 Set `GOCACHE` and stop in not Jenkins job found
  Dockerfile
  ci_jobs_trigger/libs/jenkins/utils/general.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#31 Do not fail on job
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/addons_webhook_trigger/addons_webhook_trigger.py
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/tests/addons_webhook_trigger/test_addons_webhook_trigger.py
  ci_jobs_trigger/tests/operators_iib_trigger/test_operators_iib_trigger.py
  ci_jobs_trigger/tests/utils.py
  ci_jobs_trigger/utils/constant.py
  config-examples/addons-webhook-trigger-config.example.yaml
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser

#33 Add missing return
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser

#35 Add README files and add comments in example yaml files
  Makefile
  README.md
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/addons_webhook_trigger/README.md
  ci_jobs_trigger/libs/openshift_ci/re_trigger/README.md
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/README.md
  ci_jobs_trigger/libs/operators_iib_trigger/README.md
  config-examples/addons-webhook-trigger-config.example.yaml
  config-examples/ci-iib-jobs-trigger-config.example.yaml
  config-examples/zstream-trigger-config.example.yaml
Labels: verified, size/L, can-be-merged, approved-myakove, branch-main

#38 add jenkins iib parameter support
  ci_jobs_trigger/libs/jenkins/utils/general.py
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/libs/utils/general.py
  ci_jobs_trigger/tests/addons_webhook_trigger/test_addons_webhook_trigger.py
  ci_jobs_trigger/tests/conftest.py
  ci_jobs_trigger/tests/operators_iib_trigger/test_operators_iib_trigger.py
  ci_jobs_trigger/tests/utils.py
  poetry.lock
  pyproject.toml
Labels: verified, size/L, can-be-merged, approved-myakove, branch-main

#41 Zstream trigger fix log warn
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser

#43 iib: add negative test, fix when no `ci_jobs` in config
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/tests/operators_iib_trigger/test_operators_iib_trigger.py
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser

#45 rename CI_JOBS_TRIGGER_PORT >> CI_JOBS_TRIGGER_LISTEN_PORT
  README.md
  ci_jobs_trigger/app.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#51 save operators iib data locally and in s3 bucket
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/operators_iib_trigger/README.md
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/tests/conftest.py
  ci_jobs_trigger/tests/operators_iib_trigger/test_operators_iib_trigger.py
  ci_jobs_trigger/utils/general.py
  config-examples/ci-iib-jobs-trigger-config.example.yaml
  poetry.lock
  pyproject.toml
Labels: verified, size/XXL, can-be-merged, approved-myakove, branch-main

#56 Rename `triggered` key to `new-iib`
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/tests/operators_iib_trigger/test_operators_iib_trigger.py
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser

#71 Zstream trigger slack webhook url optional
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/utils/general.py
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser

#73 Zstream trigger Always sleep after each iteration
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser
