Repository RedHatQE/ci-jobs-trigger, pull requests merged in 2024-02, with the labels that each got.

#2 Monitor OCP releases and trigger relevant jobs based on z-stream version
  .gitignore
  Dockerfile
  README.md
  VERSION
  ci_jobs_trigger/__init__.py
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/__init__.py
  ci_jobs_trigger/libs/zstream_trigger.py
  ci_jobs_trigger/utils/__init__.py
  ci_jobs_trigger/utils/general.py
  poetry.lock
  pyproject.toml
  tox.ini
  zstream-trigger-example.config.yaml
Labels: verified, size/XXL, can-be-merged, branch-main, approved-rnetser

#7 zstream-trigger add tests
  .gitignore
  Makefile
  ci_jobs_trigger/libs/zstream_trigger.py
  ci_jobs_trigger/tests/__init__.py
  ci_jobs_trigger/tests/zstream_trigger/__init__.py
  ci_jobs_trigger/tests/zstream_trigger/manifests/versions.py
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
  ci_jobs_trigger/utils/general.py
  poetry.lock
  pyproject.toml
  tox.ini
Labels: verified, size/XXL, can-be-merged, branch-main, approved-rnetser

#5 Add openshift ci job re trigger
  ci_jobs_trigger/app.py
  ci_jobs_trigger/libs/jenkins/__init__.py
  ci_jobs_trigger/libs/openshift_ci/__init__.py
  ci_jobs_trigger/libs/openshift_ci/re_trigger/__init__.py
  ci_jobs_trigger/libs/openshift_ci/re_trigger/job_db.py
  ci_jobs_trigger/libs/openshift_ci/re_trigger/re_trigger.py
  ci_jobs_trigger/libs/openshift_ci/utils/__init__.py
  ci_jobs_trigger/libs/openshift_ci/utils/constants.py
  ci_jobs_trigger/libs/openshift_ci/utils/openshift_ci.py
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/__init__.py
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/tests/job_retriggering/__init__.py
  ci_jobs_trigger/tests/job_retriggering/manifests/__init__.py
  ci_jobs_trigger/tests/job_retriggering/manifests/junit_operator_failed_pre_phase.xml
  ci_jobs_trigger/tests/job_retriggering/manifests/junit_operator_failed_test_phase.xml
  ci_jobs_trigger/tests/job_retriggering/test_job_triggering.py
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
  ci_jobs_trigger/utils/general.py
  config-examples/zstream-trigger-example.config.yaml
  docker-compose.yaml
  poetry.lock
  pyproject.toml
  pytest.ini
Labels: verified, size/XXL, can-be-merged, approved-myakove, branch-main

#13 Fix slack error url if fail to get job status
  ci_jobs_trigger/libs/openshift_ci/re_trigger/re_trigger.py
Labels: verified, size/XS, can-be-merged, approved-myakove, branch-main

#17 Add healthcheck
  ci_jobs_trigger/app.py
Labels: verified, size/XS, can-be-merged, approved-myakove, branch-main
