Repository RedHatQE/ci-jobs-trigger, pull requests merged in 2024-04, with the labels that each got.

#81 Add missing processed_versions_file_path in README and example
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/README.md
  config-examples/zstream-trigger-config.example.yaml
Labels: verified, size/XS, can-be-merged, approved-myakove, branch-main

#84 zstream trigger: fix trigger logic, add logs and test
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
Labels: verified, size/M, needs-rebase, can-be-merged, branch-main, approved-rnetser

#92 zstream tests: fix get_accepted_cluster_version` mock
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
Labels: verified, size/XS, branch-main

#98 zstream trigger: do not stop process after the first trigger
  .pre-commit-config.yaml
  ci_jobs_trigger/libs/addons_webhook_trigger/addons_webhook_trigger.py
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  ci_jobs_trigger/libs/operators_iib_trigger/iib_trigger.py
  ci_jobs_trigger/tests/addons_webhook_trigger/test_addons_webhook_trigger.py
  ci_jobs_trigger/tests/zstream_trigger/test_zstream_trigger.py
  ci_jobs_trigger/utils/general.py
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser, approved-omrirh

#100 Run interval from config
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  config-examples/zstream-trigger-config.example.yaml
  poetry.lock
  pyproject.toml
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser

#108 zstream move sort after set() (#94)
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
Labels: verified, size/XS, can-be-merged, approved-myakove, branch-main

#146 Z-trseam: add option to set cron format as time interval
  ci_jobs_trigger/libs/openshift_ci/ztream_trigger/zstream_trigger.py
  config-examples/zstream-trigger-config.example.yaml
  poetry.lock
  pyproject.toml
Labels: verified, size/XXL, can-be-merged, approved-myakove, branch-main, JIRA:MSINTEROP-910
